/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Kevin Bowersox' at '1/18/16 7:18 PM' with Gradle 2.9
 *
 * @author Kevin Bowersox, @date 1/18/16 7:18 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
